# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
    -   id: clang-format
        files: \.(c|cpp|cu|cuh|h)
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.28.0'
    hooks:
    -   id: yapf
